### ISSUE TITLE
Timezone está dando erro

### ISSUE THREAD

**Issue by mrebello** [projeto-siga/siga-docker#4]
O comando
RUN sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone"
está dando erro no appserver.
Comentando a linha no Dockerfile funcionou.

**Comment by DtiLegBG** [comment]
A princípio a situação estará corrigida com o merge desse PR
https://github.com/projeto-siga/siga-docker/pull/3

**Comment by dinarde** [comment]
Concluído com o Pull Request:
https://github.com/projeto-siga/siga-docker/pull/3
