### ISSUE TITLE
Alterações no Standalone.xml

### ISSUE THREAD

**Issue by Kouthk** [projeto-siga/siga-docker#5]
As alterações que realizo no arquivo [Standalone.xml](https://github.com/projeto-siga/siga-docker/blob/master/standalone.xml) não estão tendo efeito.

Mesmo reiniciando o container. 
Cheguei até mesmo a excluir os volumes e o problema persiste.
Poderia me auxiliar com isso?

**Comment by DtiLegBG** [comment]
Sempre que fizer alterações no standalone é necessário rodar docker-compose build --no-cache antes de subir o container novamente

**Comment by Kouthk** [comment]
'Docker-compose build --no-cache'  estava apresentando erro na hora da execução, realizei apenas o comando - ' docker-compose build ' e as alterações surtiram efeito.
 
 Muito obrigado!
