### ISSUE TITLE
Editor de texto não aparece ao editar documentos

### ISSUE THREAD

**Issue by lms91** [projeto-siga/siga-docker#6]
Ao criar ou editar um novo documento o editor de textos, na parte da entrevista, não é exibido. 
Verifiquei este problema ao atualizar a versão do Siga-Doc que estou testando para a  versão 10.2.4.7 utilizando o comando docker-compose build --no-cache.
Executei uma instalação limpa utilizando o docker para eliminar qualquer influencia das alterações que eu já havia feito no sistema, porém o problema persiste.

**Comment by dinarde** [comment]
@lms91 Ajustado o default da URL do CKEditor no standalone para caminho relativo, ao invés do Absoluto.

Favor realizar o build novamente e informar se resolveu.
